// src/react/CertifiedContentBadge.tsx

import React, { useState, useEffect, useRef } from 'react';
import { VerificationState, buildVerificationUrl, decodeUserSecret, fetchData } from '../core';

interface CertifiedContentBadgeProps {
  genContentId: string;
  userSecret?: string;
  proxyUrl?: string;
}

const CertifiedContentBadge: React.FC<CertifiedContentBadgeProps> = ({
  genContentId,
  userSecret,
  proxyUrl,
}) => {
  const [verificationState, setVerificationState] = useState<VerificationState>(
    VerificationState.LOADING
  );
  const [error, setError] = useState<string | null>(null);
  const badgeRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const verifyContent = async () => {
      setVerificationState(VerificationState.LOADING);
      let finalUserSecret = userSecret;

      try {
        if (proxyUrl) {
          // Secure Proxy Method
          const response = await fetchData(`${proxyUrl}?genContentId=${genContentId}`);
          if (response.verified) {
            setVerificationState(VerificationState.CERTIFIED);
          } else {
            setVerificationState(VerificationState.UNCERTIFIED);
          }
        } else {
          // Obfuscated Key Method
          if (!finalUserSecret) {
            // Look for data-cc-secret on parent elements
            let parent = badgeRef.current?.parentElement;
            while (parent) {
              if (parent.dataset.ccSecret) {
                finalUserSecret = parent.dataset.ccSecret;
                break;
              }
              parent = parent.parentElement;
            }
          }

          if (!finalUserSecret) {
            throw new Error('userSecret prop or data-cc-secret attribute is required.');
          }

          const decodedKey = decodeUserSecret(finalUserSecret);
          const verificationUrl = buildVerificationUrl(genContentId, decodedKey);
          const response = await fetchData(verificationUrl);

          if (response.verified) {
            setVerificationState(VerificationState.CERTIFIED);
          } else {
            setVerificationState(VerificationState.UNCERTIFIED);
          }
        }
      } catch (err: any) {
        setError(err.message);
        setVerificationState(VerificationState.ERROR);
      }
    };

    verifyContent();
  }, [genContentId, userSecret, proxyUrl]);

  return (
    <div ref={badgeRef}>
      {verificationState === VerificationState.LOADING && <span>Loading...</span>}
      {verificationState === VerificationState.CERTIFIED && <span>Content Certified</span>}
      {verificationState === VerificationState.UNCERTIFIED && <span>Content Not Certified</span>}
      {verificationState === VerificationState.ERROR && <span>Error: {error}</span>}
    </div>
  );
};

export default CertifiedContentBadge;

// src/angular/certified-content-badge.component.ts

import { Component, Input, OnInit, signal, ElementRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { VerificationState, buildVerificationUrl, decodeUserSecret, fetchData } from '../core';

@Component({
  selector: 'certified-content-badge',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div>
      @switch (verificationState()) {
        @case (VerificationState.LOADING) {
          <span>Loading...</span>
        }
        @case (VerificationState.CERTIFIED) {
          <span>Content Certified</span>
        }
        @case (VerificationState.UNCERTIFIED) {
          <span>Content Not Certified</span>
        }
        @case (VerificationState.ERROR) {
          <span>Error: {{ error() }}</span>
        }
      }
    </div>
  `,
})
export class CertifiedContentBadge implements OnInit {
  @Input() genContentId!: string;
  @Input() userSecret?: string;
  @Input() proxyUrl?: string;

  verificationState = signal<VerificationState>(VerificationState.LOADING);
  error = signal<string | null>(null);
  VerificationState = VerificationState; // Expose enum to template

  constructor(private elementRef: ElementRef) {}

  ngOnInit(): void {
    this.verifyContent();
  }

  async verifyContent(): Promise<void> {
    this.verificationState.set(VerificationState.LOADING);
    let finalUserSecret = this.userSecret;

    try {
      if (this.proxyUrl) {
        // Secure Proxy Method
        const response = await fetchData(`${this.proxyUrl}?genContentId=${this.genContentId}`);
        if (response.verified) {
          this.verificationState.set(VerificationState.CERTIFIED);
        } else {
          this.verificationState.set(VerificationState.UNCERTIFIED);
        }
      } else {
        // Obfuscated Key Method
        if (!finalUserSecret) {
          let parent = this.elementRef.nativeElement.parentElement;
          while (parent) {
            if (parent.dataset.ccSecret) {
              finalUserSecret = parent.dataset.ccSecret;
              break;
            }
            parent = parent.parentElement;
          }
        }

        if (!finalUserSecret) {
          throw new Error('userSecret prop or data-cc-secret attribute is required.');
        }

        const decodedKey = decodeUserSecret(finalUserSecret);
        const verificationUrl = buildVerificationUrl(this.genContentId, decodedKey);
        const response = await fetchData(verificationUrl);

        if (response.verified) {
          this.verificationState.set(VerificationState.CERTIFIED);
        } else {
          this.verificationState.set(VerificationState.UNCERTIFIED);
        }
      }
    } catch (err: any) {
      this.error.set(err.message);
      this.verificationState.set(VerificationState.ERROR);
    }
  }
}
